server:
  port: 8090

spring:
  application:
    name: gateway

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: ProductService
        uri: lb://product-service
        predicates:
        - Path=/ProductService/**
        filters:
        - RewritePath=/ProductService/(?<path>.*), /$\{path}
      - id: ShoppingCartService
        uri: lb://shopping-cart-service
        predicates:
        - Path=/ShoppingCartService/**
        filters:
        - RewritePath=/ShoppingCartService/(?<path>.*), /$\{path}
      - id: DeliveryService
        uri: lb://delivery-service
        predicates:
        - Path=/DeliveryService/**
        filters:
        - RewritePath=/DeliveryService/(?<path>.*), /$\{path}