server:
  port: 8090

spring:
  application:
    name: gateway

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: service1
        uri: lb://service1
        predicates:
        - Path=/service1/**
        filters:
        - RewritePath=/service1/(?<path>.*), /$\{path}
      - id: service2
        uri: lb://service2
        predicates:
        - Path=/service2/**
        filters:
        - RewritePath=/service2/(?<path>.*), /$\{path}